image: python:3

clone:
  depth: full

definitions:
  caches: #cache for sonar scanner
    sonar: ~/.sonar/cache
  steps:
    - step: &install-and-run-tests #install and run tests
        name: Install & Run Test
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - coverage erase
          - coverage run -m unittest -v
          - coverage xml
        artifacts: #defining the artifacts to be passed to each future step.
          - coverage.xml
    - step: &code-analysis #submit sonar scan report to sonar cloud
        name: Code Analysis
        caches:
          - sonar
        script:
          - pipe: sonarsource/sonarcloud-scan:1.0.1
    - step: &deploy-staging #deploy to lambda via sls
        name: Deploy (Staging)
        deployment: staging
        image: node:10.15.3
        caches:
          - node
        script:
          - npm install
          - sls deploy --stage staging
pipelines:
  custom: #Pipelines that can only be triggered manually
    release/staging:
      - step: *install-and-run-tests
      - step: *code-analysis
      - step: *deploy-staging
  branches:
    development: #Pipelines that will be triggered on merge
      - step: *install-and-run-tests
      - step: *code-analysis
  pull-requests: #Pipelines that will be triggered on pull request creation and update
    feature/*:
      - step: *install-and-run-tests
      - step: *code-analysis
